### ISSUE TITLE
Incorrect dynamic array sizes for some data structures after construction

### ISSUE THREAD

**Issue by drbenmorgan** [mnovak42/g4hepem#41]
In testing serialization/deserialization reads in the same data that was written, I think I've tripped across a bug in how a few sizes for dynamic arrays are set in `G4HepEmElectronData` and `G4HepEmGammaData`. In the cases I've found, the symptom is that the data member giving the size of the array is `0`, but the pointer to the array is _not_ `nullptr`. Consequently nothing is serialised for that array (I'll add additional error checking for that case!) and so round-tripping to/from file fails comparison.

The affected `(size, pointer)` pairs are:

- `G4HepEmGammaData`
  - `fElemSelectorConvNumData, fElemSelectorConvData`
- `G4HepEmElectronData`
  - `fElemSelectorIoniNumData, fElemSelectorIoniData`
  - `fElemSelectorBremSBNumData, fElemSelectorBremSBData`
  - `fElemSelectorBremRBNumData, fElemSelectorBremRBData`
 
This doesn't appear to be related to the changes in #39 as the same behaviour is observed both with and without those changes. I'm happy to do further checks and discuss/submit fixes, but wanted to report/discuss first as whilst the places where the sizes/arrays are handled are pretty isolated, the code around them touches a lot of data so the more eyes/advice the better!

**Comment by mnovak42** [comment]
Please note, that element selectors are used to in the EM simulation to select the target atom on which (the discrete part of) the interaction takes place. Therefore, **they are not needed** so **not built** (properly) 
when one of the followings are true:

 1. **the** simulation configuration contains a **detector** that **has only single element materials** (there is no much choice for target atom in materials that has a single element so we don't need target element selector at run time) -> no any target element selector is built:
   
        for **all the XY models** fElemSelectorXYNumData = 0  and  fElemSelectorXYData = new double[0]; in this case
   
 2. the **minimum energy** at which a given interaction, described by a given XY model can happen **is lower than the maximum energy** at which the model is used in all materials, materials-cuts couples that has more than one elements:

        for the **given XY model** the fElemSelectorXYNumData = 0  and  fElemSelectorXYData = new double[0]; in this case
 
      Example:

      - think about SB bremsstrahlung model that is used up to 1 GeV electron energy
      -  but it can be that the secondary gamma production threshold in a given material-cuts couple translates to a minimum energy that is higher than this 1 GeV 
      - bremsstrahlung photon emission (the discrete part) will never happen in this material-cuts couple below 1 GeV photon energy -> we will never use the SB model at run time in this material-cuts couple 
      - **we don't need to select target atoms at run time with the SB model in this material-cuts couple** 
      - if this is true for all material-cuts couples, that builts up from more than one elements, then we don't need target element selector for this model 


While I think (and also confirmed by my tests) that everything is fine here, we might easily resolve this by simple leaving the corresponding ``fElemSelectorXYData`` pointers to be ``nullptr`` in all cases when the corresponding ``fElemSelectorXYNumData = 0`` instead of the current ``fElemSelectorXYData = new double[0];``.

**Comment by drbenmorgan** [comment]
Thanks for the detailed explanation @mnovak42!

> While I think (and also confirmed by my tests) that everything is fine here, we might easily resolve this by simple leaving the corresponding `fElemSelectorXYData` pointers to be `nullptr` in all cases when the corresponding `fElemSelectorXYNumData = 0` instead of the current `fElemSelectorXYData = new double[0];`.

This sounds like the best solution - I'll prepare a PR with this change in but won't be until tomorrow.

**Comment by mnovak42** [comment]
Fine for me. 

As I updated my comment, we might need to introduce checks then in some places, especially when copying these arrays to the device (leaving also the device side array pointers to be ``nullptr`` and skip copy).

**Comment by mnovak42** [comment]
After #42, the `fElemSelectorXYData` array pointers are left to be `nullptr` when the corresponding `fElemSelectorXYNumData = 0`.
